added version string cli
greglandrum/yaehmop pull request #22
Opened 2018-12-13 23:53 UTC by richardjgowers

So when building the conda package I needed a quick way to check the binary built.. there wasn't a way to get a 0 exit code without including input files etc.  If we add a `-v` option we have a quick check that yaehmop exists.

2018-12-26 05:26 UTC, greglandrum requested changes
The change makes perfect sense. I added a couple of suggestions.

2018-12-26 05:26 UTC, greglandrum commented on tightbind/main.c
> +    fprintf(stdout, "version 1.0?\n");
might as well include the actual version in this:
```suggestion
     fprintf(stdout, "version %s\n", VERSION_STRING);
```

2018-12-26 05:26 UTC, greglandrum commented on tightbind/main.c
> +  if (strcmp(argv[1], "-v") == 0){
This block needs to go after the check on line 114; we don't know at this point whether or not we actually have an argument.

2018-12-26 05:27 UTC, greglandrum commented
@richardjgowers : sorry it took me so long to get to reviewing this.

2018-12-26 22:13 UTC, richardjgowers commented
@greglandrum ok should be good to go

2018-12-27 18:37 UTC, greglandrum approved these changes

2018-12-27 18:37 UTC, merged

2018-12-27 18:38 UTC, greglandrum commented
Thanks for those changes. If you end up making a conda package, please let me know!